apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sillypets-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus-stack        # Tells Prometheus Operator to pick up this monitor
spec:
  selector:
    matchLabels:
      app: sillypets                 # Matches metadata.labels in service.yaml
  namespaceSelector:
    matchNames:
      - default                      # Namespace where sillypets-service runs
  endpoints:
  - port: http                       # Matches ports[].name in service.yaml
    path: /metrics                   # Endpoint exposing metrics
    interval: 15s
