services:
  # Tier 1: The Relational Database System
  db:
    image: postgres:15-alpine
    container_name: sillypets-backend-db
    environment:
      POSTGRES_USER: musa_admin
      POSTGRES_PASSWORD: SuperSecurePassword123
      POSTGRES_DB: sillypets_records
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sillypets-net

  # Tier 2: The Front-End Web Application
  web:
    image: musabalaaudu/sillypets-image:V1.0
    container_name: sillypets-frontend-web
    ports:
      - "8082:80"
    networks:
      - sillypets-net
    depends_on:
      - db

  # Tier 3: Continuous Monitoring Watchdog
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - sillypets-net

  # Metrics Exporter: Collects CPU, RAM & I/O from Docker containers
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /var/run:/var/run:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "8080:8080"
    networks:
      - sillypets-net
    restart: always

  # Time-Series Database: Stores performance metrics over time
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - sillypets-net
    restart: always

  # Visual Dashboards: Renders graphs for metrics
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=SuperSecurePassword123
    networks:
      - sillypets-net
    restart: always

  # Stage 6: Continuous Integration & Automation Server
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8081:8080"  # Mapped to 8081 to avoid conflict with cAdvisor on 8080
      - "50000:50000" # Agent communication port
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Grants Jenkins ability to build Docker images
    networks:
      - sillypets-net
    restart: always

# Permanent disk storage so your data doesn't disappear when containers stop
volumes:
  pgdata:
  uptime-kuma-data:
  prometheus_data:
  grafana_data:
  jenkins_data:

# The private network mesh connecting all tiers together
networks:
  sillypets-net:
    driver: bridge