
services:
  # Tier 1: The Relational Database System
  db:
    image: postgres:15-alpine
    container_name: sillypets-backend-db
    environment:
      POSTGRES_USER: musa_admin
      POSTGRES_PASSWORD: SuperSecurePassword123
      POSTGRES_DB: sillypets_records
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sillypets-net

  # Tier 2: The Front-End Web Application
  web:
    image: musabalaaudu/sillypets-image:V1.0
    container_name: sillypets-frontend-web
    ports:
      - "8082:80"
    networks:
      - sillypets-net
    depends_on:
      - db # Forces Docker to wait until the database is up before launching the web layer

  # Tier 3: Continuous Monitoring Watchdog
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - sillypets-net

# Permanent disk storage so your data doesn't disappear when containers stop
volumes:
  pgdata:
  uptime-kuma-data:

# The private network mesh connecting all tiers together
networks:
  sillypets-net:
    driver: bridge
